### ISSUE TITLE
High Error on EuRoC Datasets

### ISSUE THREAD

**Issue by norabarlow** [ILLIXR/open_vins#8]
Hello!

I am running your standalone version of OpenVINS (using `./run_illixr_msckf`). I am noticing that your version has different accuracy than the original OpenVINS; have you experienced similar results and perhaps know the reason why? I noticed most of the changes you made were cosmetic (i.e. printing/not printing out things), unless I missed something. Below are results from the original OpenVINS (first image) and the ILLIXR OpenVINS (second image), run on `vicon_room1/V1_02_medium`:

OpenVINS:
<img width="391" alt="Screen Shot 2021-03-10 at 00 20 19" src="https://user-images.githubusercontent.com/8922256/110599146-6c97bc80-8137-11eb-9054-8c743b404e0a.png">

ILLIXR OpenVINS:
<img width="395" alt="Screen Shot 2021-03-10 at 00 21 09" src="https://user-images.githubusercontent.com/8922256/110599155-6f92ad00-8137-11eb-89ac-9c18db312bae.png">

Thanks!

**Comment by mhuzai** [comment]
Thank you for checking out ILLIXR!

This is rather odd. We tried most EuRoC sequences and got very comparable (but not identical) accuracy to the original OpenVINS. Even speaking qualitatively, the poses we got rendered correct images from the point of the view of the drone. If the errors were as high as reported above, the system would essentially be unusable. So I think there is some underlying bug here.

1. Could you please share how you got the above values?
2. Which branch/commit did you use?

**Comment by norabarlow** [comment]
To get the values above, I modified the Recorder class to not rely on ROS. It performs the same functionality and writes to the output file every time `feed_measurement_stereo()` is called. The number of poses in the resulting file is 1469 for OpenVINS and 1709 for ILLIXR OpenVINS. I am using the `posyaw` option to calculate the errors above.

I am on master, commit `97428` (the latest commit).

**Comment by mhuzai** [comment]
Hi @norabarlow, sorry for the super late response. This is our error when running OpenVINS standalone and using the `posyaw` option. But we don't use Recorder and dump out the poses ourselves (which, as you can see, causes the RPE calculation to fail). After the simulation, we use `ov_eval/src/error_singlerun.cpp` to crunch the numbers.

![image](https://user-images.githubusercontent.com/12307777/116139833-15748980-a69c-11eb-99f3-63b5ec90a14c.png)
